import React, { useEffect } from 'react'
import Head from 'next/head'
import { getUser } from "@/utils/users"


export default function Home() {
    useEffect(() => {
        getUser().then(result => {
            console.log(result)
        })
    }, [])

    return (
        <>
            <Head>
                <title>Apfco website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <h1 className="text-3xl font-bold underline">Hello Apfco</h1>
            </main>
        </>
    )
}
